boost_hot_water:
  description: Turn boost mode on for the period of time specified, or off."
  fields:
    entity_id:
      description: Name(s) of entites to change.
      example: "water_heater.hot_water"
    time_period:
      description: Time period in minutes for the boost.
      example: 30
    boost_mode:
      description: Enable boost funcion.
      example: True
